refactor: made two modules
MambaJDev/java-shareit pull request #4
Opened 2024-07-23 16:06 UTC by MambaJDev

2024-07-24 07:39 UTC, MambaJDev commented
Привет!!! Я пока отправил чтобы успеть. Не хочу переводиться. Тестами сегодня покрою gateway модуль и надеюсь проверка пройдет

2024-07-24 14:36 UTC, afomkina commented
Все проверки должны быть зелеными
<img width="1029" alt="Screenshot 2024-07-24 at 11 35 49 AM" src="https://github.com/user-attachments/assets/93405ee3-2ffe-4207-9b20-38549c303b55">

2024-07-24 16:17 UTC, MambaJDev commented
чуть-чуть не успел

2024-07-25 16:43 UTC, afomkina requested changes
Получилась отличная работа, она полностью соответствует тз и выглядит максимально чисто и структурировано 💪

2024-07-25 16:43 UTC, afomkina commented on shareit-server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Вся валидация теперь находится в модуле gateway, данная зависимость больше не нужна

2024-07-25 19:23 UTC, afomkina approved these changes

2024-07-26 10:48 UTC, merged